[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://alms-backend-api.onrender.com"

# API yönlendirmesi
[[redirects]]
  from = "/api/*"
  to = "https://alms-backend-api.onrender.com/:splat"
  status = 200
  force = true

# SPA için yönlendirme
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
