services:
  - type: web
    name: alms-backend
    env: python
    region: frankfurt  # Europe region
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false  # This will be set manually in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
    plan: starter # Free tier
