services:
  - type: web
    name: alms-backend
    env: python
    region: frankfurt  # Europe region
    buildCommand: ./render_build.sh
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        sync: false  # Render dashboard'dan ayarlanacak
      - key: SUPABASE_KEY
        sync: false  # Render dashboard'dan ayarlanacak
      - key: FRONTEND_URL
        value: "https://alms-dashboard.netlify.app"
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    plan: starter # Free tier
