services:
  - type: web
    name: alms-backend
    env: python
    region: frankfurt  # Europe region
    buildCommand: ./render_build.sh
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        sync: false  # Render dashboard'dan ayarlanacak
      - key: SUPABASE_KEY
        sync: false  # Render dashboard'dan ayarlanacak
      - key: VITE_SUPABASE_URL
        fromService:
          name: alms-backend
          type: web
          envVarKey: SUPABASE_URL
      - key: VITE_SUPABASE_ANON_KEY
        fromService:
          name: alms-backend
          type: web
          envVarKey: SUPABASE_KEY
      - key: FRONTEND_URL
        value: "https://alms-frontend.onrender.com"  # Frontend URL'i güncelleyin
      - key: CORS_ORIGINS
        value: "https://alms-frontend.onrender.com,http://localhost:5173"  # CORS izin verilen originler
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    plan: starter # Free tier

  - type: web
    name: alms-frontend
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_SUPABASE_URL
        fromService:
          name: alms-backend
          type: web
          envVarKey: SUPABASE_URL
      - key: VITE_SUPABASE_ANON_KEY
        fromService:
          name: alms-backend
          type: web
          envVarKey: SUPABASE_KEY
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
