services:
  - type: web
    name: alms-backend
    env: python
    region: frankfurt  # Europe region
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SUPABASE_URL
        sync: false  # Render dashboard'dan ayarlanacak
      - key: SUPABASE_KEY
        sync: false  # Render dashboard'dan ayarlanacak
      - key: FRONTEND_URL
        value: "https://alms-dashboard.netlify.app"
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: true
    plan: starter # Free tier
